name: Dev Build

on:
  push:
    branches:
      - ublish-dev/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build ./Mindbox.Data.Linq.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-build -c Release

      - name: Pack
        run: dotnet pack ./Mindbox.Data.Linq.sln -c Release -p:BuildNumber=${{ github.run_number }} -p:VersionTag="-dev"

      - name: Publish
        run: dotnet nuget push **/*.nupkg -k ${{secrets.MINDBOX_NUGET_AUTH_TOKEN}} -s https://www.nuget.org/api/v2/package